### ISSUE TITLE
np.fromstring is deprecated

### ISSUE THREAD

**Issue by BrianPugh** [tvogels/pyexr#11]
`np.fromstring` [here](https://github.com/tvogels/pyexr/blob/master/pyexr/exr.py#L241) is deprecated:

```
/usr/local/lib/python3.6/dist-packages/pyexr/exr.py:241: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
    np.fromstring(strings[i], dtype = precision) \
```

It looks like there are slight nuances between fromstring and from buffer (read only, perhaps byte order, who knows) so I wasn't comfortable making the change myself.

**Comment by tvogels** [comment]
Hi @BrianPugh, 

Thanks for the report. I'm not actively using this library myself at the moment. If you use it on a regular basis, I'd be fine with changing this and seeing if things break.

Thijs

**Comment by BrianPugh** [comment]
I'll make a pull request in the coming week; i'll play around with it

**Comment by toaarnio** [comment]
Would it be possible to make a new release to PyPI with this issue fixed? Thanks!

**Comment by tvogels** [comment]
Yes, this is in version 0.3.9 which is now on PyPI.

**Comment by toaarnio** [comment]
Great, thank you!
