### ISSUE TITLE
Where the 'depth' variable comes from

### ISSUE THREAD

**Issue by JustinAsdz** [tvogels/pyexr#14]
Hi ,

Thanks for the great work,
while I'm trying to reproduce the **WRITING part result** as the readme file wrote,  I have no idea where the **'depth' variable** comes from, can you shade me a light.

Thanks

**Comment by tvogels** [comment]
Hi,

Like  'color' and 'normal', 'depth' is meant to represent just another component that you may want to save in an EXR file.
You can fill it with any numpy array.

Does that clarify things?

Thijs

**Comment by JustinAsdz** [comment]
Hi Thijs, 
Thanks for your quick reply, and I seem to have understand the needs of storing a exr file---- it's about what you need.

Thanks again.
Yours
