### ISSUE TITLE
Problem using image data in pillow

### ISSUE THREAD

**Issue by Gus-The-Forklift-Driver** [tvogels/pyexr#24]
Using this code : 
```import pyexr
from PIL import Image as im
import numpy as np


file = pyexr.open("frame_0000.exr")
img = file.get("Image")
data = im.fromarray(img, 'RGBA')
data.show()
```
On this image : 
![source exr layer](https://i.imgur.com/4SeehLW.png)
I get this : 
![result png](https://i.imgur.com/7xdi9Ut.png)

[here](https://file.io/SZSXFP849UJZ) is the source file

I need the png image to be the same as the image from the exr.
Or in python extract a specific layer from an exr image.

**Comment by tvogels** [comment]
Hi! Did you solve this issue? Was it an issue with pyexr? Is it loading the image incorrectly or does pillow not show it right?

**Comment by Gus-The-Forklift-Driver** [comment]
No i shill have the issue, I belive it is comming from the data from pyexr not beeing interpreted propely by pillow. But I have no clue how to fix this. 
An example on how to make that work would be great.

**Comment by tvogels** [comment]
Hi, sorry I’m not actively maintaining this project anymore, and don’t have the bandwidth to look into this. Maybe you can try reading the image with another library like openimageio first.
