### ISSUE TITLE
Release 0.3.11 to PyPI

### ISSUE THREAD

**Issue by BrianPugh** [tvogels/pyexr#25]
Hey tvogels! I was wondering if you could make a patch release to pypi containing the changes from the past few years? thanks!

**Comment by ChristopheMoreau** [comment]
Hey, maybe adding the multipart support ? 🙏

**Comment by tvogels** [comment]
Hi, thanks for the message. Would one of you be willing to take ownership
of pyexr? I don’t use this anymore myself, and don’t have the capacity to
maintain it properly. I’d be happy to transfer pypi credentials to you.

**Comment by BrianPugh** [comment]
I'd be more than happy to take over. Can you add me as a maintainer both here and on pypi? My pypi username is also [BrianPugh](https://pypi.org/user/BrianPugh/)

Thanks!

**Comment by tvogels** [comment]
Done! Thanks Brian!

**Comment by meshula** [comment]
Hi from the OpenEXR project! Not that long ago, the openexrpython project was donated to the OpenEXR project itself, for which we are very grateful. We are interested in evolving the project and improving the ergonomics over time. If it's of interest to the pyexr team, one avenue forward could be to bring the interfaces from pyexr over to the main OpenEXR project and combine efforts.

**Comment by tvogels** [comment]
That sounds like a good idea to me.

**Comment by BrianPugh** [comment]
Sounds good! Right now I'm "modernizing" the repo with type hints and stuff. I'll be cutting a release with that stuff in the next day or two. After that, I think we should definitely try to integrate the projects!

**Comment by BrianPugh** [comment]
@tvogels I need a few more things (I don't have permissions to edit pyexr settings):

1. Can you go to https://pypi.org/manage/project/pyexr/settings/ and create a token; limit the scope to just `pyexr`. Then add it to https://github.com/tvogels/pyexr/settings/secrets/actions under the name `PYPI_TOKEN`.

2. Optionally (but nice!) goto https://app.codecov.io/gh and generate a token for pyexr. Then add it to https://github.com/tvogels/pyexr/settings/secrets/actions under the name `CODECOV_TOKEN`.

**Comment by tvogels** [comment]
Done

**Comment by BrianPugh** [comment]
v0.4.0 has been released! @meshula we can open up a new issue and discuss integration once the dust settles a bit.
