### ISSUE TITLE
Adding header interface

### ISSUE THREAD

**Issue by yellowtailfan** [tvogels/pyexr#5]
I think it would be great to be able to read and write the EXR header from pyexr. In particular, I'd like to be able to access the header attributes and add custom attributes.

Would you be interested in a patch with this feature? I think it could be implemented quite simply as an optional feature for users who need it without cluttering the basic interface.

**Comment by tvogels** [comment]
This sounds like a nice feature to have. PR would be very welcome! Would be great if we can make sure that the basic api doesn't change.

**Comment by yellowtailfan** [comment]
Great thanks for your feedback!

Meanwhile, my apologies, but my plans have changed so I'm not working on this right now. But good to know it would have your support if I come back to it.
