### ISSUE TITLE
Release to PyPi

### ISSUE THREAD

**Issue by BrianPugh** [tvogels/pyexr#6]
Hi @tvogels ,

I was wondering if you could bump the version and release the new version of pyexr to pypi? Thanks!

**Comment by tvogels** [comment]
Hi @BrianPugh, this should work now. Somehow the version on Pypi was already 0.3.6 while the one on github was still 0.3.5. Changed it to 0.3.7 and uploaded the current code.

**Comment by BrianPugh** [comment]
Thank you so much!

**Comment by smerzbach** [comment]
Hey Thijs, a new bump and PyPI release would be great, as writing support in the current 0.3.7 release is a bit broken. Thanks in advance!

**Comment by tvogels** [comment]
Done. Thanks for the message.

**Comment by BrianPugh** [comment]
@tvogels hey tvogels! can you release the current master? Thanks!

**Comment by tvogels** [comment]
Done, thanks @BrianPugh
