### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by electronicliujiang** [tvogels/pyexr#8]
OpenEXR.so: undefined symbol: _ZNK3Imf14TypedAttributeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE12writeValueToERNS_7OStreamEi

**Comment by electronicliujiang** [comment]
![image](https://user-images.githubusercontent.com/38310357/78362185-43e47a00-75ec-11ea-8f8e-c45d110f6322.png)

**Comment by tvogels** [comment]
Hey! Thanks for reporting this issue. This seems to be an issue with a dependency of this project, [OpenEXR](https://github.com/jamesbowman/openexrpython). I'd suggest you open the same issue there. I'll close the ticket here for now.
